server:
  port: 8899

route:
  # 路由策略：random-随机、loop-轮询
  type: random

zk:
  # zk地址
  address: 112.74.171.15:2181
  # zk上记录 服务ip的根节点
  path: /serverIp
  timeout:
    # 链接超时时间 ms
    connect: 10000
    # seesion超时时间 ms
    session: 10000

