zk:
  # zk地址
  address: 112.74.171.15:2181
  # zk上记录 服务ip的根节点
  node:
    server: /serverIp
  timeout:
    # 链接超时时间 ms
    connect: 10000
    # seesion超时时间 ms
    session: 10000

im:
  server:
    # websocket监听端口
    port: 10011
  ping:
    # 30000ms没有收到客户端心跳，关闭channel
    timeout: 30000
    # 重连次数
  reconnect:
    max-count: 3

spring:
  redis:
    host: 112.74.171.15
    port: 6379
    password: root
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        max-wait: 1000
        min-idle: 10